### ISSUE TITLE
Grammar Feedback

### ISSUE THREAD

**Issue by Ovid** [Ovid/Cor#2]
Use this issue to leave [feedback on the Cor grammar](https://github.com/Ovid/Cor/wiki/Cor-Grammar/).

**Comment by Abigail** [comment]
VERSION     ::= 'v' DIGIT '.' DIGIT {DIGIT}

So, you can have 10 versions (if you start counting at 0), and then it's game over? That's just one more than cats get, and three less than time lords get. ;-) I guess it's just a typo, and you really want `'v' DIGIT {DIGIT} '.' DIGIT {DIGIT}`.

But why exactly one period? Some people like dotless version numbers (like DNS uses), others prefer two (which Perl itself uses) or more. And since this is Perl, you probably want to specify whether version 4.2 lies between versions 4.1 and 4.3, or between 4.199 and 4.201.

**Comment by cxw42** [comment]
Good point.  I would personally rather inherit the existing version-number flexibility (and weirdness) of Perl 5 than have to remember yet another versioning scheme :) .  Therefore, if the leading `v` is required, I think the rest should be limited to v-strings that `version` will accept.

(refs: the grammar in [version::regex](https://metacpan.org/source/JPEACOCK/version-0.9924/lib/version/regex.pm).  Also, [CPAN::Meta::Spec](https://metacpan.org/pod/CPAN::Meta::Spec#Version-Formats), [version::Internals](https://metacpan.org/pod/distribution/version/lib/version/Internals.pod))

**Comment by Ovid** [comment]
@Abigail For now, I've changed it to a three-part v string. Thanks for your comments!

@cxw42 The only reason to leave version numbers the way they are now is because of backwards-compatibility with a horribly broken system. However, if we do that, we can't reliably compare version numbers and that destroys many of the benefits we're trying to get by having a "better" OO system.

**Comment by cxw42** [comment]
@Ovid vX.Y.Z is fine with me :) .  For clarity, same v-string semantics as `version` 0.77+?  I.e., same comparison rules, but no semver restrictions on what the parts of the v-strings mean?

I believe we do not need to support any kind of pre-release indicator (`vX.Y_Z`).  Yes?  It would be worth documenting that in the spec either way so it's clear what we are and are not carrying forward from the past.

**Comment by duncand** [comment]
If we want Corinna to do better we'll also want to include an authority attribute and not just a version attribute, if not up front then leaving that open for a possible later addition.

**Comment by Ovid** [comment]
This is resolved for the MVP. Further issues should be new tickets.
