### ISSUE TITLE
Explicitly discuss why things are different from Moo(se) and Class::Accessor etc.

### ISSUE THREAD

**Issue by robrwo** [Ovid/Cor#34]
I keep reading the documentation and thinking "this is called 'x' in Moose why is it called 'y' in Cor?"

So I think a small paragraph (one or two sentences) explaining why something has a different name or a different function/method name will be helpful, not just in the RFCs but for people coming from those object systems.

**Comment by Ovid** [comment]
This is part of [the RFC checklist](https://github.com/Ovid/Cor/issues/28). It mostly focuses on Moo/se. There are (last I counted), about 80+ CPAN modules to handle some aspects of OO, and I've encountered hand-rolled ones at clients. I can't cover all of them, so I mostly focused on Moo/se since they've traditionally been the winners. I've covered some of these topics in videos [here](https://www.youtube.com/watch?v=7tsgVSctqXk) and [here](https://www.youtube.com/watch?v=FO5ift28RyE).

Thus, I'll close this out because it will be covered in the checklist.
