### ISSUE TITLE
"Rationale" feedback

### ISSUE THREAD

**Issue by bill-mcgonigle** [Ovid/Cor#81]
I'm trying to follow your LRU cache example.

It's declared:
```
    has $cache    :handles(get) = Hash::Ordered->new;
```
and then the explanation says:
```
has $cache :handles(get) :builder;
method _build_cache () { Hash::Ordered->new }
...
"if someone calls ->get on this this class, attempt to delegate it to whatever we have in this slot. In this case, that's the value the :builder method returns, in this case, Hash::Ordered->new;
```
OK, so hold up. Is :builder a special object method type or a declared method name?  Is _build_VARNAME a magic method name?   Is this somehow implicitly constructed (because it's not declared in the example code)?

It's likely I missed something but, as #feedback, this wasn't clear to me how the sample code got to that explanation.

**Comment by Ovid** [comment]
Hi @bill-mcgonigle. That appears to be from the [Rationale](https://github.com/Ovid/Cor/wiki/Rationale) wiki page. At the top of that document it states:

> [Please see the main page of the repo for the actual
RFC](https://github.com/Ovid/Cor). As it states there:
>
> > Anything in the Wiki should be considered "rough drafts."

Documents in the wiki were used to reflect the decision of the Corinna team as the proposal was evolving and they should no longer be considered canonical. They're incomplete (as you've noticed) and are often wrong. I've left them up there because many people have linked to them.

Instead, I refer you to [the full RFC](https://github.com/Ovid/Cor/blob/master/rfc/toc.md) and, in particular, [the MVP which is actively being added to the Perl core now](https://github.com/Ovid/Cor/blob/master/rfc/mvp.md).
