### ISSUE TITLE
Roles Feedback

### ISSUE THREAD

**Issue by Ovid** [Ovid/Cor#9]
Use this issue to provide feedback on the [Roles Proposal](https://github.com/Ovid/Cor/wiki/Roles).

**Comment by haarg** [comment]
I don't find arguments about silently changing behavior due to classes overriding role methods particularly convincing. Inheritance has the exact same issue.

Roles probably need to be able to provide behavior like the `ADJUST` and `DESTRUCT` methods shown elsewhere. Having these be "methods" may not be the best approach. As mentioned elsewhere, the pattern used in Moose/Moo looks like:
```
sub BUILD {}
after BUILD => sub { ... };
```
This is not obvious to do. Also this requires method modifiers, which are excluded from this proposal for roles. Having them be separate keywords or something similar may make sense. But allowing roles to have behavior tied to construction or destruction prevents them from being commutative. This includes attributes with immediate defaults. But I don't think preventing roles from having any construction time behavior is viable.

Excluding method modifiers to preserve commutative properties that are already not guaranteed is a mistake, I believe.

**Comment by Ovid** [comment]
@HaraldJoerg A roles does not have access to the slots or other innards of the consuming class. Instead, if that class provides public methods (even via `:reader` or `:writer`), then the role can use those.

Yes, private methods should be sufficient for the `requires` predicate.

**Comment by maros** [comment]
I miss a 'does' (or similar) method to check on an object if a particular behavior/interface is supported. One could use 'can' instead and check for a particular method name, but this is prone to accidental name conflicts. Not sure if this belongs into the role rfc, though.

**Comment by Ovid** [comment]
@haarg wrote:

> I don't find arguments about silently changing behavior due to classes overriding role methods particularly convincing. Inheritance has the exact same issue.

Given that roles were invented and later formalized to fix the problems with inheritance, I think that should answer the question. Heck, this is enough of an issue with _inheritance_ that Java introduced the `@Override` annotation to instantly let developers know that something was going on.

In traits, the researchers modified the Smalltalk browser to signal to developers that a method was "shadowing" a role method. It was never intended to be silent action at a distance. Wondering why role isn't functioning the way I expect because I've silently replaced the `fun` method isn't fun. Corinna is supposed to be fixing problems, not holding on to old problems.

> Excluding method modifiers to preserve commutative properties that are already not guaranteed is a mistake, I believe.

I believe we've gotten to the point where I _reluctantly_ agree with this, but we've punted on this behavior for V1. Given that the majority of OO languages out there seem to be able to do without method modifiers suggests to me that we should at least see what comes out of this for Corinna.

Your other points about `ADJUST` and `DESTRUCT` are taken. They're now included in roles (darn it), along with slot initialization, but I don't think they _necessarily_ break commutativity unless they operate on conflicting state (though there's a high chance of that)

**Comment by Ovid** [comment]
@HaraldJoerg asked:


> Does a role have access to the slots or other innards of the consuming class?

No.

> Is a private method sufficient to fulfill a requires predicate for a role?

Not at this time, because a role cannot see private methods in other namespaces.

At some point we'll need to address this. Java has a similar issue with interfaces in that they can't do much with protected methods, so everything via interfaces is public. This, I think, is a mistake. However, I want to tread lightly here because it seems like this is easy to get wrong. Thus, is seems more of a V2 feature.

**Comment by Ovid** [comment]
With reluctance, closing this because it doesn't seem to impact the accepted MVP.
